### ISSUE TITLE
可否自动读取 MWeb 的外部文档设置？

### ISSUE THREAD

**Issue by echohn** [tianhao/alfred-mweb-workflow#10]
我注意到 MWeb 3.0 外部文档的设置在 `~/Library/Containers/com.coderforart.MWeb3/Data/Library/Application Support/externalSourceItems.data` 这里，如果能读取其中配置的话，是不是就可以不用自己设置了？

<img width="757" alt="image" src="https://user-images.githubusercontent.com/5844475/42071914-8c99d13a-7b90-11e8-89e8-ca1604e7b5dd.png">

**Comment by tianhao** [comment]
我还没有试用3.0，不过如果可以读出来可以加上去，试试吧

**Comment by tianhao** [comment]
```
$ defaults read externalSourceItems.data
2018-06-29 20:57:27.554 defaults[15455:911612]
Domain externalSourceItems.data does not exist
```
无法读取文件
