### ISSUE TITLE
mo指令文档库位置显示目录不存在，无法识别${HOME}

### ISSUE THREAD

**Issue by fcwork** [tianhao/alfred-mweb-workflow#12]
# mo指令填写文档库位置只能用绝对路径
- mo指令，用${HOME}/xxx时无法找到路径，可以使用绝对路径/Users/xxx/xxx，但是在iMac多用户使用时不大方便。
- moe就没有问题， 可以填${HOME}/xxx
<img width="559" alt="screen shot 2018-11-29 at 10 08 34" src="https://user-images.githubusercontent.com/43286431/49195023-5c250300-f3c0-11e8-9990-6c2e664c08cc.png">

Alfred调试模式截图
<img width="854" alt="screen shot 2018-11-29 at 10 13 00" src="https://user-images.githubusercontent.com/43286431/49195114-b9b94f80-f3c0-11e8-9f89-e9850472cf6a.png">

**Comment by tianhao** [comment]
已修复，再试试
