### ISSUE TITLE
外部文档中有的文件搜不出来

### ISSUE THREAD

**Issue by ysnows** [tianhao/alfred-mweb-workflow#13]

**Comment by tianhao** [comment]
有报什么错吗? alfred  workflow debug 是可以看到报错的

**Comment by ysnows** [comment]
![image](https://user-images.githubusercontent.com/11255869/53614684-b333b180-3c15-11e9-9ea7-33beccabd4b7.png)

![image](https://user-images.githubusercontent.com/11255869/53614710-c6df1800-3c15-11e9-878a-93a77dc6a6c4.png)

**Comment by tianhao** [comment]
可能是有的文件内容导致的, 我这边没有有问题的文件, 不好定位, 可以发一个你那边不能查到的文件的内容 (可公开的)上来吗? 我好测试定位, 当然你也可以自已定位

**Comment by ysnows** [comment]
我新建两个AndroidOs目录，然后把文件移过去，就好了~

**Comment by ysnows** [comment]
![image](https://user-images.githubusercontent.com/11255869/53618249-8091b500-3c25-11e9-9e50-15a7c219cf9c.png)
很奇怪~

**Comment by ysnows** [comment]
文件或者目录中有&符号的也搜不出来

**Comment by tianhao** [comment]
修复了, 试试看, 替换一下脚本或重新安装试试
