### ISSUE TITLE
外部文档搜索时，标题取值错误

### ISSUE THREAD

**Issue by kuonzZ** [tianhao/alfred-mweb-workflow#16]
# 问题描述
大佬你好，文档检索时，对title的取值似乎是取文件第一行的内容，而不是文件名？
当我使用外部搜索来管理hexo生成的博文时，由于文档统一带有前缀类似如下：
```
---
title: 双机调试环境搭建
date: 2020-02-14 18:37:36
updated: 2020-02-14 18:37:36
categories:
tags:
---
```
因此title全部取值为---，导致无法正常使用`moe -h`功能，如下图，还望修复。
![](http://kuon.oss-cn-chengdu.aliyuncs.com/img/2020-02-21-033348.png)
# 附上Alfred的调试信息如下：
[11:20:13.680] Logging Started...
[11:20:19.676] MWeb[Script Filter] Queuing argument ''
[11:20:19.754] MWeb[Script Filter] Script with argv '(null)' finished
[11:20:19.757] MWeb[Script Filter] {"items":[
{
"type": "file",
"title": "# 欢迎使用 MWeb",
"arg": "/Users/kuon/Documents/mWeb/docs/15822535188456.md"
}
]}
[11:20:19.838] MWeb[Script Filter] Queuing argument ''
[11:20:19.963] MWeb[Script Filter] Script with argv '(null)' finished
[11:20:19.969] MWeb[Script Filter] {"items":[
{"type": "file","title": "---","subtitle": "/Users/kuon/Documents/blog/source/_posts/折腾/博客搭建/Hexo配置及使用技巧.md","arg": "/Users/kuon/Documents/blog/source/_posts/折腾/博客搭建/Hexo配置及使用技巧.md"},

**Comment by tianhao** [comment]
两种方式, 都是改 search-ext.sh 的以下部分
![image](https://user-images.githubusercontent.com/365540/75090272-26a79f00-559c-11ea-86ac-2ddb9160c802.png)


1.  只改一个数字(推荐), 不要筛查第1行, 筛查第2行(或其它行, 你自已改数字就可以
原: final_expr="${final_expr} | egrep '^.+\.md\:1\:' | awk -F':' '{print \$1}'"
新: final_expr="${final_expr} | egrep '^.+\.md\:2\:' | awk -F':' '{print \$1}'"

2.  用文件名,但是筛查的是完整路径, 目录也会被当作是文件名, 不够精准, 改动也比较大
if [ ${#header_arr[@]} -gt 0 ];then
    for i in ${header_arr[@]}
    do
        final_expr="${final_expr} | grep -i '${i}'"
    done
fi

跟据你自已的需要改workflow中的 search-ext.sh 文件吧

**Comment by kuonzZ** [comment]
非常感谢，抱歉查收迟了，邮箱app出问题没推送

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=pengjunting&uid=pengjunting%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22pengjunting%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
pengjunting
pengjunting@outlook.com
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制

在2020年02月22日 17:56，tianhao<notifications@github.com><mailto:notifications@github.com> 写道：

两种方式, 都是改 search-ext.sh 的以下部分
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F365540%2F75090272-26a79f00-559c-11ea-86ac-2ddb9160c802.png&data=02%7C01%7C%7Cb4e7ea493e5c40975ac408d7b77d6cbc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637179621628765249&sdata=Z5Ys7VQVsdcYlMK1YkBh%2FomPoTqd27lbufIU%2FrtZDXk%3D&reserved=0>

  1.  只改一个数字(推荐), 不要筛查第1行, 筛查第2行(或其它行, 你自已改数字就可以
原: final_expr="${final_expr} | egrep '^.+.md:1:' | awk -F':' '{print $1}'"
新: final_expr="${final_expr} | egrep '^.+.md:2:' | awk -F':' '{print $1}'"

  2.  用文件名,但是筛查的是完整路径, 目录也会被当作是文件名, 不够精准, 改动也比较大
if [ ${#header_arr[@]} -gt 0 ];then
for i in ${header_arr[@]}
do
final_expr="${final_expr} | grep -i '${i}'"
done
fi

跟据你自已的需要改workflow中的 search-ext.sh 文件吧
