### ISSUE TITLE
Bug: `mo`快捷键无法打开MWeb，因为APP路径写死了。

### ISSUE THREAD

**Issue by l-qing** [tianhao/alfred-mweb-workflow#22]
这个插件非常给力，没有换其他`markdown`编辑器，完全是因为该`Alfred`插件太方便了。

最近几天，AppStore上的MWeb升级后，APP的路径发生了变化。导致无法正常打开文件。<br>
检查发现，`mo`对应的脚本中，APP路径写死了。而其他`moe`里就是使用的环境变量，不会存在该问题。

![Shot 2021 08 20 at 17 57 26](https://user-images.githubusercontent.com/9499086/130216497-2e7d6b6d-8684-4bbd-b633-325e2fdc8915.png)

<img width="1036" alt="Shot 2021 08 20 at 18 02 28" src="https://user-images.githubusercontent.com/9499086/130217088-9a9ad8a8-3d28-4c2c-91ec-9c25b5cc6413.png">

**Comment by tianhao** [comment]
我抽时间调整一下吧
