### ISSUE TITLE
关于文档打开方式的问题

### ISSUE THREAD

**Issue by chenzz** [tianhao/alfred-mweb-workflow#3]
为啥你演示截图里打开文档在新tab，我在新的打开文档出现在新window？

**Comment by tianhao** [comment]
我也没有做什么特殊的设置，我这里默认情况下，所有打开的内部文档都在一个窗口+tab，所有外部文档一个窗口+tab

**Comment by tianhao** [comment]
开发者表示下一版本会搞定这个问题。
https://github.com/oulvhai/MWeb-issues/issues/763

**Comment by chenzz** [comment]
赞~！
