### ISSUE TITLE
添加外部文档库并无法搜索到

### ISSUE THREAD

**Issue by arvinxx** [tianhao/alfred-mweb-workflow#4]
外部文档路径如下
```
${HOME}/Dropbox/Knowledge Library 知识库
```
无法识别
![image](https://user-images.githubusercontent.com/28616219/33230526-1e908bf8-d220-11e7-8c42-496b12298e12.png)

**Comment by tianhao** [comment]
已更新，再试试，你可以直接复制 shell/search_ext.sh 替换 moe 的脚本
