### ISSUE TITLE
可不可以分享下你的EditorTheme

### ISSUE THREAD

**Issue by JayFang1993** [tianhao/alfred-mweb-workflow#9]
可不可以分享下你的Editor Theme，Preview Theme，看上去挺好看的~

**Comment by tianhao** [comment]
solarized-dark/light， MWeb 自带的。
solarized Theme官网: http://ethanschoonover.com/solarized
你会发现它有各种软件的配色版本,我的Alfred、iTerm和idea 等等都是用的 solarized 主题。
